## Refer to the FaceFormer to predict the expression parameters
exp_name: full_model

log_dir: work_dir/AAAI/train_one_hot_3dmmformer
test_mode: False

checkpoint: null

model_name: Face3DMMOneHotFormer

Trainer:
  max_epochs: 20 # 120
  check_val_every_n_epoch: 1
  val_check_interval: 0.25 # [0.0, 1.0]
  num_sanity_val_steps: 0

vis_step: 250

lr: 0.0001
wd: 0.0
lr_decay_step: 20
lr_decay_rate: 0.8

dataset:
  batch_size: 1
  number_workers: 6

  train:
    dataset_name: Face3DMMOneHotDataset
    data_root: ./data/HDTF_preprocessed
    split: data/train.txt
    fetch_length: 100
    fetch_stride: 100
    
    batch_size: 1
    number_workers: 6
  
  validation:
    dataset_name: Face3DMMOneHotDataset
    data_root: ./data/HDTF_preprocessed
    split: data/train.txt
    fetch_length: 100
    fetch_stride: 100
    
    batch_size: 1
    number_workers: 6

  # audio_path: data/HDTF_preprocessed/WRA_KristiNoem0_000/WRA_KristiNoem0_000.wav
  data_root: ./data/HDTF_preprocessed
  audio_path: data/audio_samples/Silence.wav
  # video_name: train/WDA_ChrisMurphy0_000
  video_name: WDA_ChrisMurphy0_000
  training_split: data/train.txt

teacher_forcing: False
supervise_exp: False

Face3DMMFormer:
  dataset: vocaset
  feature_dim: 1024
  period: 25
  vertice_dim: 64
  use_mouth_mask: True
